version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"  # Fix: Removed "pip" (was incorrect)
  jobs:
    pre_install:
      - echo "Building ERP Questionnaire on ReadTheDocs"

python:
  install:
    - requirements: docs/requirements.txt

mkdocs:
  configuration: mkdocs.yml

